### PR TITLE
Drop most babel transforms

### PR DESCRIPTION
**Pull request by bfred-it**
As discussed in #393

### CODE REVIEW

**Comment by bfred-it** [comment]
Why are the tests failing? It doesn't show any error

**Comment by josephfrazier** [comment]
It looks like both [Chrome](https://travis-ci.org/OctoLinker/browser-extension/builds/298933583#L731-L733) and [Firefox](https://travis-ci.org/OctoLinker/browser-extension/builds/298933583#L735-L737) have some issue with assigning to `module.exports`.

**Comment by bfred-it** [comment]
What’s that line doing anyway? It looks like it runs a loop on itself

**Comment by stefanbuck** [comment]
That's a [dynamic require](https://webpack.js.org/guides/dependency-management/#require-context) which is needed to load the tests files. Not sure why your change is conflicting with reassigning of  `module.exports`, but I noticed that we can remove this line anyway. Also in the `main-packages.js`which loads the test from `/packages` doesn't need this export assignment.

**Comment by bfred-it** [comment]
Can you apply that change to this PR?

**Comment by stefanbuck** [comment]
It seems that the rebase has some effect on the build 🤷

**Comment by josephfrazier** [comment]
Huh, that's interesting. I guess it had something to do with `core-js`: https://github.com/OctoLinker/browser-extension/commit/e56f75d5b5f22bb5d27ed46775d0d056d19600b2#diff-e00d3d45185f722f3df476b178fdd069

**Pull request merged**
