### PR TITLE
Update project website url

### PR DESCRIPTION
**Pull request by stefanbuck**

### CODE REVIEW

**Comment by josephfrazier** [comment]
can we do https://octolinker.github.io/ instead?

**Comment by stefanbuck** [comment]
Why should we use https? There are no sensitive data on that page, right?

**Comment by stefanbuck** [comment]
I'm gonna merge this now. We can change it in a later version if needed 😉

**Comment by josephfrazier** [comment]
No problem. It's just that I believe https should be the default for everything if possible. Here's a decent explanation of the reasoning: https://https.cio.gov/everything/

**Pull request merged**
