### PR TITLE
Document dotnet support

### PR DESCRIPTION
**Pull request by stefanbuck**

### CODE REVIEW

**Comment by stefanbuck** [comment]
😆 true. I've created the PR on my phone and trust me, editing readmes on such a small screen isn't easy. I know this is a bad excuse for the wrong content. Will fix that tomorrow morning.

**Comment by josephfrazier** [comment]
Oh, that's no problem! Let me see if I can push the changes to the branch. 😄

**Comment by stefanbuck** [comment]
Nice collaboration 😊

**Comment by josephfrazier** [comment]
Cheers!

P.S. Github recently made this possible across forks as well, as long as the forker agrees: https://github.com/blog/2247-improving-collaboration-with-forks

**Pull request merged**
