### PR TITLE
Opening links in new tab on middle mouse click

### PR DESCRIPTION
**Pull request by stefanbuck**
Finally, it's possible to open links in a new tab on middle mouse click 🎉 

dog-home-mfw-EPwELUbhreEPC

### CODE REVIEW

**Comment by josephfrazier** [comment]
One downside I can think of with this way of solving the problem: if the user tries to select some clickable text (for example, to copy it for searching), the mouseup will cause the browser to navigate away from the page, ruining the user's select operation.

Is there another way to detect middle clicks?

**Comment by stefanbuck** [comment]
Good catch, I didn't think about that. The click event is not working when using the middle mouse on  jQuery delegate element for some reasons. On stackoverflow I found this workaround with mouseup. Let me think about. Anyway excellent spot 👍

**Comment by josephfrazier** [comment]
We might be able to use both a click event and a mouseup event, but ignore the mouseup event if it's not the middle button.

**Comment by stefanbuck** [comment]
Neat idea 👍

**Comment by stefanbuck** [comment]
By adding two event listener one for `click` and another for `mouseup` the `onClick` handler gets called twice for on a normal mouse click. I tried to prevent the mouseup event from bubbling up, but it seems to be impossible http://stackoverflow.com/questions/18342747/why-cant-a-mouseup-event-prevent-a-click-event

A flag which indicates if a click is ongoing could solve the problem, but seems to me a bit dirty to me. Do you have any better ideas?

**Comment by josephfrazier** [comment]
What if we just have `onClick` return immedialy if the `mouseup` event isn't the middle button? I pushed a branch with the changes I have in mind: https://github.com/OctoLinker/browser-extension/compare/5f1f9ef7352557da4db39c59a89269bf40c8eb58...josephfrazier:middle-mouse-click

**Comment by stefanbuck** [comment]
I updated the branch with your suggestion. Looks really good now. Thanks for the support 👍

**Comment by josephfrazier** [comment]
Ooh, with more tests too, nice! I'll go ahead and merge :D

**Pull request merged**
