### PR TITLE
Use npm script to build and pack extension

### PR DESCRIPTION
**Pull request by stefanbuck**
Based on the discussion with @josephfrazier on #101 this PR use npm script instead of gulp for building  and packing the extension. Except `npm run *-pack` it works quite well. I'm just worried about the complexity in the `package.json` file. I'm undecided which version I prefer more. 

@josephfrazier regarding the issue with `npm run *-pack`. When I run the script in the console it works, but the same script execute via npm script returns 

```
zip error: Nothing to do! (out/chrome-octolinker-4.1.0.zip)
```

Any ideas?

### CODE REVIEW

**Comment by josephfrazier** [comment]
Hmm, when I run `npm run chrome-pack`, it fails with this message:

```
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run chrome-dist && mkdir -p out && zip --recurse-paths out/chrome-octolinker-$npm_package_version.zip dist/ --exclude dist/ \* out/\* node_modules/\*
```

But when I run the suggested command above, it also fails with:

```
zip error: Nothing to do! (out/chrome-octolinker-.zip)
```

(Note that `$npm_package_version` is empty, because we're not running in the context of an npm script.) 

It looks like the `chrome-pack` command was modeled after `pack-repo`, but since it's only including the files in `dist/`, there's no need to `--exclude` anything. In particular, `dist/` is being excluded, which explains why `zip` says there's "Nothing to do!". Maybe `chrome-pack` should be this instead?

```
npm run chrome-dist && mkdir -p out && zip --recurse-paths out/chrome-octolinker-$npm_package_version.zip dist/
```

**Comment by stefanbuck** [comment]
@josephfrazier please have a look again. TA

**Comment by josephfrazier** [comment]
Ah, that looks much better! Nice find on the `zip -j` flag to avoid having `dist/` go into the zipped paths; I wasn't aware of that.

I do have one nitpick, though: My development process involves loading the unpacked Chrome extension directly from `./chrome`, but with these changes, `npm run chrome-build` doesn't actually create `./chrome/manifest.json`, so the extension fails to load. I started thinking about how to fix this, and I realized that we could do away with the `dist/` directory entirely. Does that sound ok to you? Here's a commit for it: https://github.com/josephfrazier/browser-extension/commit/b5d5300bb0ed99ca40d18674a7f14ed6a1c566d7

**Comment by stefanbuck** [comment]
My idea was to get rid of the `chrome/` and `firefox/` directory and use `dist/` instead for development. Maybe it's just a naming issue. What about `build`? The only disadvantages I can think of is that pair development in Firefox and Chrome is not possible anymore, which shouldn't be a big issue. Btw `npm run chrome-build ` produces a `manifest.json` file, under `dist/` and not as you may expected under `chrome/`.

**Comment by josephfrazier** [comment]
Oh, I see now. I was under the impression that the chrome and firefox directories were still used somewhere in the build process, but I now see that I was mistaken. I think it's cleaner to have a single output directory anyway, especially if we were to add [support for other browsers like Safari](https://github.com/OctoLinker/browser-extension/issues/29). Merging :)

**Comment by stefanbuck** [comment]
What about the naming? Should we call it `build` instead of `dist`?

**Comment by josephfrazier** [comment]
I don't really have a preference there, other than a very slight preference to leave it as `dist`, so I don't have to change the path that Chrome loads the unpacked extension from :P

**Pull request merged**
