### PR TITLE
Add AppVeyor CI

### PR DESCRIPTION
**Pull request by stefanbuck**
Support Windows CI testing through Appveyor.

### CODE REVIEW

**Comment by stefanbuck** [comment]
@josephfrazier I added AppVeyor as you suggested in #163. Unfortunately this isn't working yet. I'll have a look at it tomorrow.

**Comment by josephfrazier** [comment]
Hey, I also tried this, and ran into a few problems as well. I've worked around some of them (here's my [work-in-progress](https://github.com/josephfrazier/browser-extension/commits/c067743a4ce3ac20f68a8a0bb81638b6f54840fe)), but there's at least one blocking issue: karma can't seem to load the phantomjs plugin (here is the [build](https://ci.appveyor.com/project/josephfrazier/browser-extension/build/1.0.7)).

**Comment by stefanbuck** [comment]
Thanks for investigating @josephfrazier. I'll update this PR according to your research result.

**Comment by josephfrazier** [comment]
There's a little more to it than that, unfortunately. `npm install` has to be run with `--no-shrinkwrap --ignore-scripts`. For reference, here's the configuration I used at the time of my previous comment. The commit messages have more details about why those flags are required.

https://github.com/josephfrazier/browser-extension/blob/2b854594a079953a3e07dd341c05a5ec6e78c0f5/.appveyor.yml

**Pull request merged**
