### PR TITLE
Add golang.org to list of allowed domains for Go files

### PR DESCRIPTION
**Pull request by rgroothuijsen**
This PR addresses #372 by parsing golang.org imports. Since these import URLs already send the user to a documentation page when opened in a browser, no special parsing seems to be required.

### CODE REVIEW

**Comment by stefanbuck** [comment]
Great 👍 Just one thing, please add a test [similar to this](https://github.com/octolinker/browser-extension/blob/5d0f537f942d15737d17c224accec96b23dd9ba5/packages/helper-grammar-regex-collection/test.js#L355). It's super easy 😉

**Comment by rgroothuijsen** [comment]
Hmm, prettier complains about something, but the only difference I can see is some "⏎········" bits. Possible Linux vs. Windows CRLF issues?

**Comment by stefanbuck** [comment]
Splitting into two lines sounds good to me. Thanks for addressing my comment.

**Comment by stefanbuck** [comment]
I'm sorry, but there are still two linting issues left. You can easily fix them by running `npm run lint -- --fix`

**Comment by rgroothuijsen** [comment]
Generally true, although since the branch was created before the introduction of prettier, I'll have to update it first.

**Comment by stefanbuck** [comment]
Great, thanks

**Pull request merged**
