### PR TITLE
Release 4.2.0

### PR DESCRIPTION
**Pull request by josephfrazier**
See https://github.com/OctoLinker/browser-extension/issues/135

@stefanbuck, as we've discussed privately, I'll take a shot at doing the releases for this one. Just to confirm, here are the steps that are needed (as far as I know):

* [ ] Merge this PR
* [ ] Tag the resulting commit as `v4.2.0` and push the tag into this repo
* [ ] \(Travis automatically releases the Chrome extension, per https://github.com/OctoLinker/browser-extension/commit/2193d36d5892b7f013b64ca18b160963fb9fc926)
* [ ] `npm run package-all`
* [ ] Submit `out/firefox-octolinker-4.2.0.zip` to https://addons.mozilla.org/en-US/developers/addon/octolinker/versions#version-upload
* [ ] Submit `out/opera-octolinker-4.2.0.zip` to https://addons.opera.com/developer/package/226344/?tab=versions

### CODE REVIEW

**Comment by josephfrazier** [comment]
Oops, I forgot to put the new version in `assets/manifest.json`! I was thinking that the code only contained "4.1.0", so I replaced only that within the codebase, which meant that I overlooked the `4.1.1` in `assets/manifest.json`. I'll follow up with a new PR for version 4.2.1, which will synchronize that version with the one in `package.json`.

**Comment by stefanbuck** [comment]
Let's remove the `version` field from the `package.json` file. It's useless anyway since this is not a published npm module.

Regarding the required steps:
- Travis should attach all build version `chrome`, `firefox` and `opera` to the release tag, so there is no need to run `npm run package-all manually`.
- You also have to upload the source code for the code review process for firefox and opera.

**Comment by stefanbuck** [comment]
To avoid the unessercy version bump you can also do a force push with the fixed version this time.

**Comment by stefanbuck** [comment]
I disabled the branch protection and remove the release from GH.

**Pull request merged**
